{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":5,"timestamp":1675246184,"nonce":"y/yURv63FwDuEag3E2fQI435jhY=","metadata":{"github-id":"LE_lADOCGKeh85cYDfAzwAAAAH1McsD"},"added":["kind/bug"],"removed":[]},{"type":3,"timestamp":1675246291,"nonce":"6kGqfOAjnoQIhUHbwwp5/PpNImw=","metadata":{"github-id":"IC_kwDOCGKeh85UJmqD","github-url":"https://github.com/git-bug/git-bug/issues/1003#issuecomment-1411803779"},"message":"I think this is a valid thing we need to fix, or at least check. I think at the moment git-bug requires having an identity to pull, as it might be required to make a merge commit. That doesn't sit well with your scenario.\nI think we need to make having a user optional there, and only error when we do need to make a merge.","files":null},{"type":3,"timestamp":1691691849,"nonce":"w8Ec+ENL8o2bzlZ7LkRHlpe5wR8=","metadata":{"github-id":"IC_kwDOCGKeh85jwqIS","github-url":"https://github.com/git-bug/git-bug/issues/1003#issuecomment-1673699858"},"message":"Copy/paste my other comment:\n\n\u003e This is more of less a dup of #1003. The solution is not to have a new command, but to make `pull` fail later, only when we do need to have an identity (to merge data) instead of a hard requirement to do any pull. This would cover your scenario as you would pull data without having to do any merge (you don't have data locally yet, nothing to merge).","files":null},{"type":3,"timestamp":1691692318,"nonce":"dh7/JDTsx5yYmAZvcF9cUfCTmDU=","metadata":{"github-id":"IC_kwDOCGKeh85jwsvE","github-url":"https://github.com/git-bug/git-bug/issues/1003#issuecomment-1673710532"},"message":"That is:\n- remove that check: https://github.com/MichaelMure/git-bug/blob/master/cache/subcache.go#L543-L547\n- make sure that the called functions behave properly when `author` can be nil, fail and present the error properly to the user when we need an `author` but don't have one","files":null}]}