{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":5,"timestamp":1672769565,"nonce":"ZxSCapt/vuZHwsYtDgh6wcb5odU=","metadata":{"github-id":"LE_lADOCGKeh85acZhIzwAAAAHlfCSf"},"added":["area/bridge"],"removed":[]},{"type":3,"timestamp":1672769785,"nonce":"R3Pi+V9WaGzRDH8ecLraiWzR5tU=","metadata":{"github-id":"IC_kwDOCGKeh85Rqc-M","github-url":"https://github.com/git-bug/git-bug/issues/973#issuecomment-1370083212"},"message":"@5nord FYI\n\nLooks like that:\n- Gitlab released a new version with new kind of event\n- the gitlab bridge assign `EventUnknown` to those when they are not recognized (dropping the details of the event) (for example https://github.com/MichaelMure/git-bug/blob/e762290e237f1e62916e17a901d1f819960d3378/bridge/gitlab/event.go#L144)\n- the gitlab bridge return an error when such an `EventUnknown` occurs: https://github.com/MichaelMure/git-bug/blob/9b98fc06489353053564b431ac0c0d73a5c55a56/bridge/gitlab/import.go#L332\n\nThat last part is problematic as it's quite reasonable for gitlab to add more events. Point number 2 could also be a problem, depending on how we look at it. I suppose we should just ignore the unknown events. Currently it fails the import of that particular issue (it doesn't commit).\n@buestad any idea what kind of event that could be, if you look at the issues that fail to import?\n\nAs for the push problem it could be related to that first problem but I suspect it's a different one. The CI does work though, so that could be specific to that new gitlab version.","files":null}]}