{"author":{"id":"d438a2fae67ddff8af5b8a1209e17c32aa4ec753e2779593dbcf334d3dc1db00"},"ops":[{"type":1,"timestamp":1669523408,"nonce":"kkxRZNmWF55y+cTd0MptV3jZFtM=","metadata":{"github-id":"I_kwDOCGKeh85XVyOT","github-url":"https://github.com/git-bug/git-bug/issues/934","origin":"github"},"title":"0.8.0 issue with Authentication","message":"I setup 0.8.0 (Linux amd64) in WSL running Ubuntu 20.04 (focal) and git 2.25.1\n\nI tried with an Org GH Repo, Personal GH repo and a freshly pulled AzDO repo.\n\n```\n$ git bug pull\nFetching remote ...\nError: authentication required\n```\n\nI tried with 0.7.2 without issue.\n\nI even tried migrating a working repo then using 0.8.0 and got the error again\n```\n...snip\nMigration #3\nPurpose: Make bug and identities independent from the storage by making the ID generation self-contained. Also, migrate to the new full DAG entity data model.\n\nidentity 1b5c437: migrated to 73519a0\nbug b3d0ba7: migrated to 025f7c3\n\n\nDone!\nbuilder@DESKTOP-72D2D9T:~/Workspaces/testgitbug$ git bug ls\nA lock file is present but the corresponding process is not, removing it.\nBuilding identity cache... Done.\nBuilding bug cache... Done.\n025f7c3 open    Bug Title 1                                             Isaac Johnson\nbuilder@DESKTOP-72D2D9T:~/Workspaces/testgitbug$ git bug pull\nFetching remote ...\nError: authentication required\n```","files":null}]}