{"author":{"id":"d82e3b0277388fab1285e702dfba0ce3b709e1919233977abaeab636c4c57550"},"ops":[{"type":3,"timestamp":1653828910,"nonce":"iMBJjYF5iEUuSXCOM4RpplxHFSw=","metadata":{"github-id":"IC_kwDOCGKeh85D-cpH","github-url":"https://github.com/git-bug/git-bug/issues/742#issuecomment-1140443719"},"message":"@mnaderhirn - Can you provide a bit of information about your OS and about your remote repository.  Also, please post the output of the following command:\n\n```\ngit config --list | grep credential\n```\n\nThis (non-error?) message appears to be from the remote repository and reports of this \"extra output\" appear to be related to the `credential-manager-core` project's rename (https://github.blog/2022-04-07-git-credential-manager-authentication-for-everyone/).  In some reports, the following command fixes the problem (though I'm not sure why authentication continues to work afterwards):\n\n```\ngit config --global --unset credential.helper\n```\n\nNote that it's also possible that this setting is in the repository's configuration - `\u003crepo\u003e/.git/config`.  Does this message also get displayed when you simply run `git push` instead of `git bug push`?","files":null}]}