{"author":{"id":"2736a5c2d173651f4143a267aebf5b50f8cb7111a44939e30cec3e98a3615d4a"},"ops":[{"type":3,"timestamp":1725368643,"nonce":"IZNdjSVl8Ubv3t4/zCuhpH2a5uU=","metadata":{"github-id":"IC_kwDOCGKeh86Kqy5n","github-url":"https://github.com/git-bug/git-bug/issues/1142#issuecomment-2326474343"},"message":"I see the same issue, when trying to add bugs to an existing git repo. \nEnvironment: Windows 10, Powershell 5.1.22621.3958\n\nSteps to reproduce\n```\nmkdir test_repo\ngit init\nNew-Item .gitignore\ngit add .\\.gitignore\ngit commit -m 'add: .gitginore'\ngit bug user create\ngit bug add -t 'testbug' -m 'description' \n \n```\nResult: \n```\nError: rename C:\\Users\\\u003cmyusername\u003e\\test_repo\\.git\\objects\\pack\\tmp_obj_3021921222 C:\\Users\\\u003cmyusername\u003e\\test_repo\\.git\\objects\\e6\\9de29bb2d1d6434b8b29ae775ad8c2e48c5391: Access is denied. \n```\nThe reason is that the files in `objects` are write-protected since they should never be modified by design of git.\n\nHowever, when i initialize an empty repo and add a bug first before doing any other commits, this seems to work fine:\n```\nmkdir test_repo2\ncd test_repo2\ngit init\ngit bug user create\ngit bug add -t 'title' -m 'description'\n\u003efb67815 created\nNew-Item .gitignore\ngit commit -m 'add: .gitginore'\ngit bug add -t 'title2' -m 'description2'\n\u003e1bbb20e created","files":null}]}