{"author":{"id":"1c0be4c7efe4cf70011d270a87e33999699eb0e9a5b12f84e0369f90dae3dacd"},"ops":[{"type":3,"timestamp":1616879004,"nonce":"lG/RoWEiCzLJUIB5hHEChVaU+V8=","metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDgwODgwMjA1NA==","github-url":"https://github.com/git-bug/git-bug/issues/606#issuecomment-808802054"},"message":"At the moment I do not know where the error happens exactly (reproducing the error takes a lot of time). Just looking at the error message it should originiate from somewhere below the call to `repo.NewBugRaw()`.\n\nThe cause might be the same as described in the issue which causes the error. There the cause was a `bufio.Scanner` (which has `bufio.MaxScanTokenSize` equal to 65536). The solution which the golang people found was to replace the `bufio.Scanner` by a `bufio.Reader` as described in https://go-review.googlesource.com/c/tools/+/93439/","files":null},{"type":6,"timestamp":1616883741,"nonce":"vklVLWpv8b6RuoCrNWUtE9VRkjI=","metadata":{"github-id":"MDE1OlVzZXJDb250ZW50RWRpdElzc3VlQ29tbWVudEVkaXQ6NDQ2NzU5MDI2"},"target":"77c3fd3faffc1e4b379b8ef9b7bb106a4ad1169c9b872ec8bc3c54e2ea0f3ff5","message":"At the moment I do not know where the error happens exactly. Just looking at the error message it should originiate from somewhere below the call to `repo.NewBugRaw()`.\n\nThe cause might be the same as described in the issue which causes the error. There the cause was a `bufio.Scanner` (which has `bufio.MaxScanTokenSize` equal to 65536). The solution which the golang people found was to replace the `bufio.Scanner` by a `bufio.Reader` as described in https://go-review.googlesource.com/c/tools/+/93439/","files":null}]}