{"author":{"id":"46cd44f31415945f2a75664577fe8217fa7d6b8c64998ffd2534046ceb867b4d"},"ops":[{"type":1,"timestamp":1747112138,"nonce":"k32dILCu5Lpajf4rOU+V+4BVdN4=","metadata":{"github-id":"I_kwDOCGKeh862UPb7","github-url":"https://github.com/git-bug/git-bug/issues/1416","origin":"github"},"title":"git: support authenticated http(s) remotes","message":"When I try to use the push (o) and pull (i) features I get these error messages:\n\nPush:\n\n```\nError                                                  \nauthentication required: Repository not found.\n```\n\nPull:\n\n```\nError                                                 \ndone                                                 \n```\n\nThere errors are surrounded with their corresponding boxes in TUI\n\nOften the pull command gives the same error as the push commands. For example, I pulled all bugs from my repo using the corresponding GitHub bridge, and then I opened the TUI and tries to do a pull and I got the same error as push.\n\nI configured my bridge as in the documentation and I can push and pull perfectly in CLI","files":null}]}