{"author":{"id":"78b2dbcd26fa0221bca7081971079c1e6d73d9ba0038b8f00744d143926f7d68"},"ops":[{"type":1,"timestamp":1697128800,"nonce":"ywWRK7hAQObrdMlu78jQVSJQfZs=","metadata":{"github-id":"I_kwDOCGKeh85zp86_","github-url":"https://github.com/git-bug/git-bug/issues/1122","origin":"github"},"title":"push fails on local origin","message":"Version is: 0.8.0 Windows 10 64 (downloaded binary)\nUsing git bash\n\nI work on a local copy with the repository set on a samba hard disk linked to my router. `git push` works fine and `git bug push` worked fine (i guess) the first time. After that, any bug push request results in \n\n```\n$ git bug push\nError: unpack error: index-pack abnormal exit\n```\n\nAm I doing something wrong?\n\n(btw wrong place  I know but amazing work - this app command is a real life saver)","files":null}]}