{"author":{"id":"0476ea1147266080938402d76671a8ea166567667d3a5b5522ece109b4da567a"},"ops":[{"type":1,"timestamp":1709907399,"nonce":"H7mDhjHe7mj6p1vQAV+eAyuRlc4=","metadata":{"github-id":"I_kwDOCGKeh86BtRio","github-url":"https://github.com/git-bug/git-bug/issues/1142","origin":"github"},"title":"Windows: \"access denied\" when creating a bug","message":"Been testing this out. If I make a local git repo, everything seems fine, but if I clone a remote repo, and try to use it I get an error:\n\n(in a Windows command window)\n```\n\u003e git clone https://server/git/git_bug_test\n\u003e cd git_bug_test\n\u003e git-bug user create\nName [me]:\nEmail [me@fake.com]:\nAvatar URL:\n\nbbc5207b0d2ddb8b823d53052a3a77eafc996a03143c3bed99f5841c2438e921\n\n\u003e git-bug add -t \"First Bug\" -m \"Bug number one!\"\nError: rename E:\\temp\\git_bug_test\\.git\\objects\\pack\\tmp_obj_2131903459 E:\\temp\\git_bug_test\\.git\\objects\\e6\\9de29bb2d1d6434b8b29ae775ad8c2e48c5391: Access is denied.\n```\n\nI can manually edit/rename the mentioned files just fine, no locks or access limits, so maybe it something else throwing the error with a spurious message?","files":null}]}