{"author":{"id":"3998add589f6a09cf4bdf0e85e5481d2c48b8a757edd699a79a0c929ab5005db"},"ops":[{"type":5,"timestamp":1661858601,"nonce":"qKzrf08gbPXdxargy3OUptfSYZU=","metadata":{"github-id":"LE_lADOCGKeh85PzTKpzwAAAAGyUIRx"},"added":["area/cli"],"removed":[]},{"type":5,"timestamp":1661858611,"nonce":"thjrzECexhqeG93I540oeQfhQVM=","metadata":{"github-id":"UNLE_lADOCGKeh85PzTKpzwAAAAGyUIjQ"},"added":[],"removed":["area/cli"]},{"type":3,"timestamp":1661858706,"nonce":"Om2T1Qlk6zm7ReUOPNnP70Rlkc0=","metadata":{"github-id":"IC_kwDOCGKeh85JZ64E","github-url":"https://github.com/git-bug/git-bug/issues/845#issuecomment-1231531524"},"message":"Any idea when you created that original repo? There is a good chance that's data created when I was still working on the data model, before everything got stabilized properly.","files":null}]}